// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

#define INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(TagName) extern INVENTORYCORE_API FNativeGameplayTag TagName;

namespace FragmentTags
{
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(GridFragment)
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(IconFragment)
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(StackableFragment)
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(ConsumableFragment)
	
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemNameFragment)
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(PrimaryStatFragment)
	
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemTypeFragment)
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(FlavorTextFragment)
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(SellValueFragment)
	INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(RequiredLevelFragment)
	
	namespace StatMod
	{
		INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_1)
		INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_2)
		INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_3)
	}
	
	namespace Rarity
	{
		INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Common)
		INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Uncommon)
		INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Rare)
		INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Epic)
		INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Legendary)
	}
}

#undef INVCORE_DECLARE_GAMEPLAY_TAG_EXTERN
